### ISSUE TITLE
Consistant Network Dropage

### ISSUE THREAD

**Issue by k1ran-ak** [ashoksoni/rrOTA#1]
whenever I open Whatsapp, hike, phone apps there is a network drops everytime

**Comment by ashoksoni** [comment]
Known issue and can't be fixed by me. Don't expect it to be fixed by vendor and the support is dead from there, if somehow someone from los do something about this, good else learn to live with it.

**Comment by k1ran-ak** [comment]
But that's the main thing you need in everyone's phone there is a frequent
network dropage while opening certain apps that includes mainly the Phone
app with which we need network for all time but it is not there and
Whatsapp which we send messages instantly but thats not happening in this
rom and hike the same story as of whatsapp It's a Major Issue regardless
the rom is good !

**Comment by ashoksoni** [comment]
Then report this to lineage or oneplus, I can't do anything in this regard.
